# Generated by Django 3.2 on 2021-05-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
